# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gládio Cítrico
email: hermespasser@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Onde criadores, loucos e excêntricos se reúnem.
baseurl: "/" # the subpath of your site, e.g. /blog

# This must be "" in localhost and hermespasser.github.io when pushed.
url: "https://hermespasser.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# custom
siteurl: hermespasser.github.io

# Build settings
markdown: kramdown
# theme: minima
# plugins:
  # - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - README.md
  # - Gemfile
  # - Gemfile.lock
