# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gládio Cítrico
email: hermespasser@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My website
# I'm using it as normal url just 'cause is working. Must leave empty in localhost
# or else i must change all links to {{site.url}}/{{site.baseurl}}/file
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# custom
siteurl: hermespasser.github.io

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
    syntax_highlighter: rouge
# theme: minima
# plugins:
  # - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by /{{site.url}}/{{site.baseurl}}. Create a custom list
# to override the /{{site.url}}/{{site.baseurl}} setting.
exclude:
  - README.md
  - build.rb
  # - Gemfile
  # - Gemfile.lock
